import { build } from 'esbuild';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getLegacyRedirects } from '../src/lib/seo-routes';

const webRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');

export async function buildDeployment(outDir: string): Promise<void> {
  const dist = resolve(outDir);
  const redirects = getLegacyRedirects();
  const pages: string[] = [];
  async function scan(directory: string) {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const path = resolve(directory, entry.name);
      if (entry.isDirectory()) await scan(path);
      else if (entry.name.endsWith('.html')) {
        const html = await readFile(path, 'utf8');
        if (/http-equiv=["']refresh["']/i.test(html)) continue;
        const route = `/${relative(dist, path).replace(/\\/g, '/').replace(/index\.html$/, '')}`;
        pages.push(route);
        if (/^\/insights\/[^/]+\/$/.test(route)) redirects[`/en${route}`] = route;
      }
    }
  }
  await scan(dist);
  const sorted = Object.entries(redirects).sort(([a], [b]) => a.localeCompare(b));
  await writeFile(resolve(dist, '_redirects'), sorted.flatMap(([from, to]) => [
    `${from} ${to} 301`, ...(from.endsWith('/') ? [`${from.slice(0, -1)} ${to} 301`] : [])
  ]).join('\n') + '\n');
  // Deployed by Docker outside the web root; block this file if copied as an asset.
  const nginx = ['# Generated by build-deployment.ts. Included inside server {}.'];
  for (const [from, to] of sorted) {
    for (const source of from.endsWith('/') ? [from, from.slice(0, -1)] : [from]) {
      nginx.push(`location = ${source} { return 301 ${to}$is_args$args; }`);
    }
  }
  for (const page of pages.filter(path => path.endsWith('/') && path !== '/')) {
    nginx.push(`location = ${page.slice(0, -1)} { return 301 ${page}$is_args$args; }`);
    if (/^\/(?:en\/)?registry\/page\/\d+\/$/.test(page)) {
      const main = page.replace(/page\/\d+\/$/, '');
      nginx.push(`location = ${page} { if ($seo_has_filters = 1) { return 301 ${main}$is_args$args; } try_files $uri $uri/ =404; }`);
    }
  }
  await writeFile(resolve(dist, '_nginx-redirects.conf'), nginx.join('\n') + '\n');
  const pagination = ['# Generated legacy pagination map, included at http scope.', 'map "$uri:$arg_page:$seo_has_filters" $seo_page_redirect {', '  default "";'];
  for (const prefix of ['', '/en']) {
    const main = `${prefix}/registry/`;
    pagination.push(`  "${main}:1:0" "${main}";`);
    for (const page of pages.filter(path => path.startsWith(`${main}page/`))) {
      pagination.push(`  "${main}:${page.match(/page\/(\d+)/)?.[1]}:0" "${page}";`);
    }
  }
  pagination.push('}', 'map $args $seo_page_query {', '  default "";', '  ~^page=[^&]*&(?<seo_after>.+)$ "?$seo_after";', '  ~^(?<seo_before>.+)&page=[^&]*&(?<seo_after_tail>.+)$ "?$seo_before&$seo_after_tail";', '  ~^(?<seo_before_end>.+)&page=[^&]*$ "?$seo_before_end";', '}');
  await writeFile(resolve(dist, '_nginx-pagination.conf'), pagination.join('\n') + '\n');
  await writeFile(resolve(dist, '_routes.json'), JSON.stringify({ version: 1, include: ['/*'], exclude: ['/_astro/*', '/fonts/*', '/og.png', '/skillflux-mark.svg'] }, null, 2));
  await writeFile(resolve(dist, '.assetsignore'), '_worker.js\n_nginx-redirects.conf\n_nginx-pagination.conf\n');
  await build({
    entryPoints: [resolve(webRoot, 'edge/worker.ts')],
    outfile: resolve(dist, '_worker.js'), bundle: true, format: 'esm', platform: 'browser', target: 'es2022',
    define: { __SEO_REDIRECTS__: JSON.stringify(redirects), __SEO_PAGES__: JSON.stringify(pages) },
    minify: true
  });
  console.log(`Generated HTTP redirects (${sorted.length}) and edge indexing rules.`);
}
